### ISSUE TITLE
SSL error on scraper

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/the_hills#2]
Scraper is no longer working on morph, however, tested locally and it is working.

Already logged an issue in morph = https://github.com/openaustralia/morph/issues/1088

```
/app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
    from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `block in connect'
    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
    from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/http.rb:751:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent.rb:508:in `connection_for'
    from /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent.rb:788:in `request'
    from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
    from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from scraper.rb:8:in `<main>'
```

**Comment by LoveMyData** [comment]
Looks like it is fixed

**Comment by henare** [comment]
@LoveMyData weird that you've come across one like this that's suddenly working yet had to implement workarounds for that issue on other scrapers you've recently worked on :thinking:

**Comment by LoveMyData** [comment]
Something is turned off becuase it is no longer report how many pages
scraped.

**Comment by henare** [comment]
@LoveMyData Yes, that's correct: https://github.com/openaustralia/morph/issues/1135
